using System.Collections.Generic;

namespace ChessCore.Modes
{
    /// <summary>
    /// Represents a game piece factory. Can be used to retrieve the options for the game mode's allowed pieces.
    /// </summary>
    public interface IPieceFactory
    {
        /// <summary>
        /// Creates a new piece based on the supplied id.
        /// </summary>
        /// <param name="id">Piece ID</param>
        /// <param name="player">Piece player</param>
        /// <returns>A new piece based on the piece type generated by the supplied id</returns>
        public GamePiece GetPiece(int id, int player);

        /// <summary>
        /// Generates options for the pieces supported by the standard mode. Generated option IDs can then be used in the <c>GetPiece(int id, int player)</c> method.
        /// </summary>
        /// <returns>An enumerable containing the options</returns>
        public IEnumerable<Option> GetPieceOptions();

        /// <summary>
        /// Generates options for the pieces supported by the standard mode. Generated option IDs can then be used in the <c>GetPiece(int id, int player)</c> method.
        /// </summary>
        /// <param name="ids">IDs to generate the options for</param>
        /// <returns>An enumerable containing the options</returns>
        public IEnumerable<Option> GetPieceOptions(IEnumerable<int> ids);
    }
}
